name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  SUPABASE_DATABASE_URL: ${{ secrets.SUPABASE_DATABASE_URL }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
        with:
          bun-version-file: .tool-versions

      - run: bun i --frozen-lockfile
      - run: bun run gen-types
        if: github.event_name != 'pull_request'
        # skip on PRs since secret context is not available
      - run: bun run lint --fix

      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944 # v1.3.1
        if: always()
        with:
          commit-message: |
            style: autofix

            [skip netlify]
